feat: filtering and sorting offer list
mcksyrek/booking-platform-client pull request #11
Opened 2020-11-02 22:57 UTC by mcksyrek

2020-11-03 09:19 UTC, mcksyrek commented on src/app/offers/toolbar/toolbar.component.scss
> +    ::ng-deep .mat-form-field-infix {
I know that ng-deep is deprecated but I have not found any other way to set style inside Angular Material Select component w/o editing library files

2020-11-03 09:55 UTC, ArtemLunt requested changes

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/offers/toolbar/toolbar.component.scss
> +    ::ng-deep .mat-form-field-infix {
That is fine

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/offers/toolbar/toolbar.component.scss
> +      width: 90vw !important;
That is not.
Pls overload this with selectors specificity.

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/shared/utils/filterOffers.ts
> +  );
Pls reduce the complexity.
Here we do have a `O(n^2)` in a worst case and it doesn't seems to be optimized.

Probably it would be better to build a set of the `allowedAttributeValues` before filtering. In this case complexity would be `O(2n)`, coz building of the set is a definitely `O(n)` and getting of the value from set is constant in the most of the cases, so `n + (n * 1) = 2n`.

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/shared/utils/sortOffers.ts
> +import { IOffer } from '@booking/offers/offer.interface';
Pls move this one into the service as well.

P.S.
In angular we're usually using `kebab-case.naming` for a files, pls dont use `camelCase` for it.

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/shared/utils/filterOffers.ts
> +export function filterObjectsListByAttributeValue<T>(
This function concerns exact functionality, so it doesn't seems to be shared. Pls move it into the offers service.
(it may be even static)

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/shared/utils/sortOffers.ts
> +}
It would be much more extensible to make a `comparator` instead of the sorting function.
In this case we'd be able to reuse this comparator for other cases when this one would be comfortable as well.

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/shared/enums/sorting-types.enum.ts
> +}
We never using `Enum` as a Enum's postfix.

2020-11-03 09:55 UTC, ArtemLunt commented on src/app/shared/classes/abstract-subscriber.ts
> +  protected addSubscriptions(subscriptions: Subscription[]): void {
What's the problem with `...`?

2020-11-03 10:10 UTC, mcksyrek commented on src/app/shared/classes/abstract-subscriber.ts
> +  protected addSubscriptions(subscriptions: Subscription[]): void {
`Type 'Subscription[]' is missing the following properties from type 'Subscription': closed, _parentOrParents, _subscriptions, unsubscribe, and 2 more.`

2020-11-03 10:10 UTC, ArtemLunt commented on src/app/offers/state/offers.state.ts
> +  }
You have to update the `customizedOffers` list on the offers list update as well.

2020-11-03 12:30 UTC, mcksyrek commented on src/app/shared/utils/sortOffers.ts
> +}
will keep sorting function but move comparator to `utils`

2020-11-03 12:51 UTC, mcksyrek commented on src/app/shared/utils/filterOffers.ts
> +  );
haha this is already done in `toolbar.component.ts`! passed down `allowedAttributeValues` is array made of set! I have to do this operation for building filters values (no point to keep it fixed for eg. cities -> what if there is no offer from some city and this city is this city in filters? ) after generating set out of values it is turned to an array due to Angular Material req! 

but ok, lets repeat building set here in future case when passed down `allowedAttributeValues` may not be built out of set :)

2020-11-03 21:19 UTC, ArtemLunt requested changes

2020-11-03 21:19 UTC, ArtemLunt commented on src/app/offers/offers.service.ts
> +    );
`new Set(allowedAttributeValues)` is going to be shorter

2020-11-03 21:19 UTC, ArtemLunt commented on src/app/offers/offers.service.ts
> +      Array.from(uniqueAttributes).includes(object[attribute])
[Interesting solution](https://thumbs.gfycat.com/EnviousInferiorJuliabutterfly-size_restricted.gif)

2020-11-03 21:19 UTC, ArtemLunt commented on src/app/offers/offers.service.ts
> +      Array.from(uniqueAttributes).includes(object[attribute])
Ok, now there's `n + n * (n + n) = O(n + 4n^2)` instead of `O(n^2)`, not bad!
Where's the first operand `n` is the conversion of array into the set, and the second one `n * (n + n)` is the loop, internal loop and internal conversion of the set into array.

I meant to use `Set#has` method

2020-11-04 23:57 UTC, mcksyrek commented on src/app/offers/offers-list/offers-list.component.ts
> +      this.offers$.subscribe(offersList => (this.offersList = offersList))
[it is eslint issue](https://eslint.org/docs/rules/no-return-assign), prettier does it automatically and it is not recommended to disable it

2020-11-05 18:21 UTC, ArtemLunt commented on src/app/offers/offers-list/offers-list.component.ts
> +      this.offers$.subscribe(offersList => (this.offersList = offersList))
Sorry, i've just got that you're doing some assignment here.
In this case i'd be better to use curves instead `{`.

2020-11-05 18:29 UTC, ArtemLunt approved these changes

2020-11-05 18:36 UTC, merged