feat: get offers from BE
mcksyrek/booking-platform-client pull request #7
Opened 2020-10-08 20:52 UTC by mcksyrek

2020-10-09 14:16 UTC, ArtemLunt requested changes

2020-10-09 14:16 UTC, ArtemLunt commented on src/app/app.module.ts
> +    HttpClientModule,
Were probably using the `HttpClient` all over, so pls create some shared module and move it there.

2020-10-09 14:16 UTC, ArtemLunt commented on src/app/shared/interceptors/server-url.interceptor.ts
> +  }
Interceptor is redundant here.
Pls handle it with the [proxy](https://angular.io/guide/build#proxying-to-a-backend-server).

2020-10-09 15:12 UTC, mcksyrek commented on src/app/shared/interceptors/server-url.interceptor.ts
> +  }
that's schweppes

2020-10-09 17:20 UTC, mcksyrek commented on src/app/shared/enums/endpoints.enum.ts
> +  Offers = '/api/offers',
I need `/api` to recognize this request by proxy - is there any elegant way to concat it with all API req? or this one is cool?

2020-10-12 11:09 UTC, ArtemLunt requested changes

2020-10-12 11:09 UTC, ArtemLunt commented on src/app/shared/enums/endpoints.enum.ts
> +  Offers = '/api/offers',
Pls rid of this prefix here

2020-10-12 11:09 UTC, ArtemLunt commented on src/proxy.conf.json
> +  "/api": "http://localhost:8080"
Here you can use `pathRewrite` to add the `/api` prefix and simply map all the requests

2020-10-12 11:19 UTC, ArtemLunt requested changes

2020-10-12 11:19 UTC, ArtemLunt commented on src/app/offers/offers.service.spec.ts
> +      service.getOffersList().subscribe(offers => {
usually it works in next way:
`spyOn(service, 'method').and.returnValue(mockResponse)`

2020-10-15 09:55 UTC, ArtemLunt approved these changes

2020-10-15 09:55 UTC, ArtemLunt commented on src/app/offers/offer-form/offer-form.component.spec.ts
> +      const spy = jest.spyOn(component.submitForm, 'emit');
Pls, provide more meaningful variable name

2020-10-15 09:55 UTC, ArtemLunt commented on src/app/offers/offers-list/offers-list.component.ts
> +    this._store.dispatch(GetOfferListAction);
`GetOfferListAction` is the class. It should be `new GetOfferListAction()`.

2020-10-15 09:55 UTC, ArtemLunt commented on src/environments/environment.ts
> +  serverUrl: '/api',
It's not a URL, it's a prefix

2020-10-15 15:41 UTC, merged