feat: basic layout implementation
mcksyrek/booking-platform-client pull request #9
Opened 2020-10-25 21:08 UTC by mcksyrek

2020-10-26 12:39 UTC, mcksyrek commented on src/app/layout/layout.service.ts
> +  readonly menuAction$ = this.menuSubject.asObservable();
move that feature to store

2020-10-26 13:00 UTC, ArtemLunt requested changes

2020-10-30 10:46 UTC, ArtemLunt requested changes

2020-10-30 10:46 UTC, ArtemLunt commented on src/app/app-routing.module.ts
> +          import('./offers/offers.module').then(m => m.OffersModule),
Btw, rare fact: you can use the ts aliases and even index files here, such a `import('@booking/offers').then(...)`.
It is not necessary at all, but it would be probably comfortable for you if you'll decide to change the project structure for some reason.

(and also in the some cases it would be shorter)

2020-10-30 10:46 UTC, ArtemLunt commented on src/app/layout/layout.state.ts
> +    ctx.setState(patch({ menuAction: !prevState }));
Just some mental gymnastic:
Try to implement the [custom operator](https://www.ngxs.io/advanced/operators#custom-operators) toggle for a boolean values.

2020-10-30 10:46 UTC, ArtemLunt commented on src/app/layout/menu/menu.component.scss
> +  &__content {
Break

2020-10-30 10:46 UTC, ArtemLunt commented on src/app/layout/menu/menu.constant.ts
> +];
I believe that those values should be in enum and this array should be typed.

2020-10-30 10:46 UTC, ArtemLunt commented on src/app/layout/menu/menu.constant.ts
> +];
Basically, you can simply make a enum and take a values using `Object#values`

2020-10-30 10:46 UTC, ArtemLunt commented on src/app/offers/offer-form/offer-form.component.spec.ts
> +        phoneNumber: ['', Validators.required],
Don't you going to validate the phone number in some way?

2020-10-30 10:46 UTC, ArtemLunt commented on src/styles/_mixins.scss
> +  @media all and (max-width: $small-screen) {
Break

2020-10-30 10:46 UTC, ArtemLunt commented on src/styles/_mixins.scss
> +}
When i've suggested to make a mixins on the media stuff i've meant something like that:
```
@mixin medium-width {
   @content;
}
```

and use it in the next way:

```
@include medium-width {
   background-color: red;
}
```

In this case you can specify the values for a different sizes in a really simple way not overloading the code with all those `@media`

2020-10-30 21:56 UTC, mcksyrek commented on src/app/layout/layout.state.ts
> +    ctx.setState(patch({ menuAction: !prevState }));
usefull

2020-10-30 21:59 UTC, mcksyrek commented on src/app/offers/offer-form/offer-form.component.spec.ts
> +        phoneNumber: ['', Validators.required],
TODO added, this PR is not about offerForm, next one is

2020-10-30 22:02 UTC, mcksyrek commented on src/styles/_mixins.scss
> +}
that nice, I did not know Sass `@content`

2020-10-30 23:00 UTC, mcksyrek commented on src/app/layout/menu/menu.constant.ts
> +];
your solution would be schweppes but this this file has changed on new branch and it stores not only item text but also routeLink, so array of objects is better than enum here
`export const MENU_LIST_ITEMS = [
  { name: 'Browse offers', route: Routes.Offers + Routes.All },
  { name: 'Create new offer', route: Routes.Offers + Routes.New },
];
`

2020-11-01 20:11 UTC, ArtemLunt requested changes

2020-11-01 20:11 UTC, ArtemLunt commented on src/app/layout/layout.state.ts
> +}
1) We can make this operator more abstract to use it for toggling of the booleans in other states. Pls call it `toggle` or something like that and move it to shared stuff (`shared/store/operators` or smth like that).
2) [Here](https://github.com/arturovt/store/blob/86fc513a5da214b7b4f678b9a826d472f61b02bc/packages/store/operators/src/insert-item.ts) you can find an example of the particular state property's operator implementation. I guess it would be much cleaner to make it looking in the next way:

```
setState(patch({
   toggleMenu: toggle()
}))
```

2020-11-01 20:11 UTC, ArtemLunt commented on src/app/offers/offers-list/offers-list.component.scss
> +@import 'src/styles/mixins';
https://stackoverflow.com/questions/57164159/stylepreprocessoroptions-angular-8

2020-11-01 20:11 UTC, ArtemLunt commented on src/app/shared/constants/icons.constant.ts
> +  'electrician',
Enum pls ;^)

2020-11-01 20:13 UTC, ArtemLunt commented on src/app/layout/menu/menu.constant.ts
> +];
Ok then

2020-11-01 21:31 UTC, merged